### ISSUE TITLE
2nd reply

### ISSUE THREAD

**Issue by kuz-sysadmin** [beardog108/MicroTXT#14]
Warning: DOMDocument::loadHTML(): htmlParseStartTag: misplaced <html> tag in Entity, line: 2 in /********** line 114

Warning: DOMDocument::loadHTML(): htmlParseStartTag: misplaced <body> tag in Entity, line: 2 in /********** line 114

Warning: Cannot modify header information - headers already sent by (output started at /srv/disk2/****** on line 178

**Comment by beardog108** [comment]
Unsupported
