### ISSUE TITLE
Posts become corrupted when using certain alphabets/characters

### ISSUE THREAD

**Issue by eArabic** [beardog108/MicroTXT#3]
Hello
Thank you very much for this wonderful script.
There is a problem in dealing with the Arabic language, especially when Reply to the article.

**after  Reply  problem  text  Arabic language**

![020](https://cloud.githubusercontent.com/assets/24383546/21385316/1184160c-c77f-11e6-8291-1bb7425e1183.png)

**Before Reply  Ok**

![010](https://cloud.githubusercontent.com/assets/24383546/21385319/154927dc-c77f-11e6-8d60-95ada7591fa0.png)

**Comment by beardog108** [comment]
Hey, @eArabic, thanks for taking the time to file your issue. 

I appreciate the details & screenshots.

If you'll give me some time, I should be able to have a fix for you within a day or so.

**Comment by eArabic** [comment]
Thank you so much .
Sorry for the spelling mistakes, I do not know English well in writing.
I will wait for you to solve the problem, and once again thank you very much

**Comment by beardog108** [comment]
I believe I have fixed the issue in this commit here: https://github.com/beardog108/MicroTXT/commit/d1b494f0f630c6429b88b72d29efff615040d212

I am closing this issue unless this doesn't work for you. 

Thank you for your detailed & polite report, I apologize if the issue caused you any inconvenience.

**Comment by eArabic** [comment]
Thank you so much,
Now it works very excellent and without problems.
Thank you for the speed of solving the problem.

![a1](https://cloud.githubusercontent.com/assets/24383546/21389511/306b1f0c-c793-11e6-99fb-b155de28de22.png)
